routes/web.php
<?php

Route::resource('blog', 'BlogController');
Route::resource('outdoors', 'OutdoorsController');
Route::resource('rest', 'RestController');
Route::resource('hrenotive', 'HrenotiveController');
Route::resource('notebook', 'NotebookController');
Route::resource('zhitie', 'ZhitieController');


Route::get('/{year}', 'BlogController@getPostsByYear')->where('year', '[0-9]+');
Route::get('/{year}/{month}', 'BlogController@getPostsByMonth')->where('year', '[0-9]+');

// Other

Route::get('/miskhakische-logo', function () {
	return typograf(view('miskhakische-logo')->with('langs'));
})->name('miskhakische-logo');


// Utils

Route::get('/login',function () {
	return view('login');
});

Route::post('/register',[
	'uses' => 'UserController@postRegister',
	'as' => 'register'
]);

Route::post('/signin',[
	'uses' => 'UserController@postSignIn',
	'as' => 'signin'
]);

Route::get('/logout',[
	'uses' => 'UserController@getLogout',
	'as' => 'logout'
]);



// Blog

Route::get('/rubrics', 'BlogController@getRubrics')->name('rubrics');
Route::get('/rubrics/{rubricSlug}', 'BlogController@getPostsByRubric')->name('blog_posts_by_rubric');

Route::get('/tags', 'BlogController@getTags')->name('tags');
Route::get('/tags/{tagName}', 'BlogController@getPostsByTag')->name('blog_posts_by_tag');

Route::get('/new-post', 'BlogController@newPost');

Route::get('/api/blog/{slug}', 'BlogController@getPostData');

Route::get('/api/outdoors/{slug}', 'OutdoorsController@getPostData');

Route::post('/api/blog/{slug}', 'BlogController@savePostData');

Route::get('/edit/{slug}', 'BlogController@edit')->name('blog.edit');
Route::get('/{slug}', 'BlogController@show')->name('blog.show');

Route::get('/', 'BlogController@index')->name('blog.index');

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use Auth;
use LengthAwarePaginator;

use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Redirect;

use App\BlogPost;
use App\BlogRubric;
use App\BlogTag;

use Carbon\Carbon;

class BlogController extends Controller
{
	public function typ($str) {
		// TODO: change 

		$new_string = str_replace(" - ", "&nbsp;&mdash; ", $str);


		// TODO: quotes, quotes inside quotes, joint small words, joint numbers, joint abbreviaions

		// $new_string = str_replace(" \"", " &laquo", $new_string);
		// $new_string = str_replace("\" ", "&raquo ", $new_string);

		return $new_string;
	}

	public function parser($str) {

		$str = preg_replace('/"(.*?)"/', '&laquo;$1&raquo;', $str);
		$str = preg_replace('/\*\*(.*?)\*\*/', '<strong>$1</strong>', $str);
		// $str = preg_replace('/\/(.*?)\//', '<em>$1</em>', $str);
		
		$str = preg_replace('/^/', '<p>', $str);
		$str = preg_replace('/$/', '</p>', $str);

		$str = preg_replace('/\r\n\r\n/', '</p><p>', $str);

		$str = preg_replace('/\r\n/', '<br />', $str);

		$str = preg_replace('/---/', '&mdash;', $str);
		$str = preg_replace('/--/', '&ndash;', $str);

		$str = preg_replace('/\[img\s([-a-zA-Z0-9]+)\s(\d+)\]/', '<img src="/images/blog/$1/$2.jpg" />', $str);
		$str = preg_replace('/<p>(\<img.*?>)<\/p>/', '$1', $str);

		$str = preg_replace('/(\bи\b\s)/', '$1&nbsp;', $str);

		return $str;
	}

	public function index()
	{
		include(app_path() . '/functions/datetime_formats.php');

		$posts = BlogPost::where('status', Auth::check() ? '>' : '=', Auth::check() ? 0 : 2)
			->orderBy('date', 'desc')
			->paginate(50);

		// $postsByYears = BlogPost::where('status', Auth::check() ? '>' : '=', Auth::check() ? 0 : 2)
		// 	->orderBy('date', 'desc')->get();

		$rubrics = BlogRubric::orderBy('name')->withCount('posts')->get();
		$tags = BlogTag::orderBy('name')->withCount('posts')->get();

		for ($i = 0; $i < count($posts); $i++) { 
			if($posts[$i]->experimental) {
				$posts[$i]->body = $this->parser($posts[$i]->body);
			}
		}

		return $this->typ(view('blog.index', ['posts' => $posts, 'rubric' => null, 'tag' => null, 'rubrics' => $rubrics, 'tags' => $tags, 'year' => null, 'month' => null]));
		// return $postsByYears;
	}

	public function create()
    {
    	if (Auth::user() && Auth::user()->id == 1) {
        	return view('blog.create');
        } else {
        	return view('login');
        }
    }

    public function store()
    {
    	if (Auth::user() && Auth::user()->id == 1) {
	        $rules = array(
	            'title' => 'required',
	            'slug' => 'required|unique:blog_posts',
	            'body' => 'required',
	        );

	        $validator = Validator::make(Input::all(), $rules);

	        // process the login
	        if ($validator->fails()) {
	            return Redirect::to('blog/create')
	                ->withErrors($validator)
	                ->withInput(Input::except('password'));
	        } else {
	            // store
	            $post = new BlogPost;

	            $post->title = Input::get('title');
	            $post->slug = Input::get('slug');
	            $post->date = Input::get('custom_date') ? Input::get('date') : date('Y-m-d H:i:s');
	            $post->status = Input::get('status');
	            $post->body = Input::get('body');
	            $post->experimental = 1;

	            $post->save();

	            // redirect
	            return Redirect::to('blog');
	        }
    	} else {
        	return view('login');
        }
    }

	public function show($slug)
	{
		include(app_path() . '/functions/datetime_formats.php');
		$post = BlogPost::where('slug', $slug)->firstOrFail();
		return view('blog.show', ['post' => $post]);
	}

	public function edit($slug)
	{
		if (Auth::user() && Auth::user()->id == 1) {
			$post = BlogPost::where('slug', $slug)->firstOrFail();
			return view('blog.edit', ['post' => $post]);
    	} else {
        	return view('login');
        }
	}

	public function update($slug)
    {
    	if (Auth::user() && Auth::user()->id == 1) {
	        $rules = array(
	            'title' => 'required',
	            'slug' => 'required',
	            'date' => 'required',
	            'body' => 'required',
	        );
	        $validator = Validator::make(Input::all(), $rules);

	        // process the login
	        if ($validator->fails()) {
	            return Redirect::to('blog/' . $slug . '/edit')
	                ->withErrors($validator)
	                ->withInput(Input::except('password'));
	        } else {
	            // store
				$post = BlogPost::where('slug', $slug)->firstOrFail();

	            $post->title = Input::get('title');
	            $post->slug = Input::get('slug');
	            $post->date = Input::get('date');
	            $post->status = Input::get('status');
	            $post->body = Input::get('body');
	            
	            $post->update();

	            // redirect
	            return Redirect::to('blog');
	        }
    	} else {
        	return view('login');
        }
    }

    public function destroy($id)
    {
    	if (Auth::user() && Auth::user()->id == 1) {
	        // delete
	        $post = BlogPost::find($id);
	        $post->delete();

	        // redirect
	        return Redirect::to('blog');
    	} else {
        	return view('login');
        }
    }

    //////////////////////

	public function getPostsByRubric($rubricSlug)
	{
		include(app_path() . '/functions/datetime_formats.php');

		$rubrics = BlogRubric::orderBy('name')->withCount('posts')->get();
		$tags = BlogTag::orderBy('name')->withCount('posts')->get();

		$rubric = BlogRubric::where('slug', $rubricSlug)->first();
		$posts = BlogPost::where('rubric_id', $rubric->id)
			->where('status', Auth::check() ? '>' : '=', Auth::check() ? 0 : 2)
			->orderBy('date', 'desc')
			->paginate(50);

		return view('blog.index', ['rubric' => $rubric, 'tag' => null, 'posts' => $posts, 'month' => null, 'rubrics' => $rubrics, 'tags' => $tags, 'year' => null]);
	}

	public function getPostsByTag($tagName)
	{
		include(app_path() . '/functions/datetime_formats.php');

		$rubrics = BlogRubric::orderBy('name')->withCount('posts')->get();
		$tags = BlogTag::orderBy('name')->withCount('posts')->get();

		$tag = BlogTag::where('slug', $tagName)->first();
		$posts = BlogPost::where('rubric_id', $rubric->id)
			->where('status', Auth::check() ? '>' : '=', Auth::check() ? 0 : 2)
			->orderBy('date', 'desc')
			->paginate(50);

		return view('blog.index', ['rubric' => null, 'tag' => $tag, 'posts' => $posts, 'month' => null, 'rubrics' => $rubrics, 'tags' => $tags, 'year' => null]);
	}

	public function getPostsByYear($year)
	{
		include(app_path() . '/functions/datetime_formats.php');

		$rubrics = BlogRubric::orderBy('name')->withCount('posts')->get();
		$tags = BlogTag::orderBy('name')->withCount('posts')->get();

		$posts = BlogPost::whereYear('date', '=', $year)
			->where('status', Auth::check() ? '>' : '=', Auth::check() ? 0 : 2)
			->orderBy('date', 'desc')
			->paginate(50);

		return view('blog.index', ['posts' => $posts, 'rubric' => null, 'tag' => null, 'rubrics' => $rubrics, 'tags' => $tags, 'year' => $year, 'month' => null]);
	}

	public function getPostsByMonth($year, $month)
	{
		include(app_path() . '/functions/datetime_formats.php');
		
		$rubrics = BlogRubric::orderBy('name')->withCount('posts')->get();
		$tags = BlogTag::orderBy('name')->withCount('posts')->get();

		$posts = BlogPost::whereYear('date', '=', $year)->whereMonth('date', '=', $month)
			->where('status', Auth::check() ? '>' : '=', Auth::check() ? 0 : 2)
			->orderBy('date', 'desc')
			->paginate(50);

		return view('blog.index', ['posts' => $posts, 'rubric' => null, 'tag' => null, 'rubrics' => $rubrics, 'tags' => $tags, 'year' => $year, 'month' => $month]);
	}

	// API
	public function getPostData($slug)
	{
		return BlogPost::where('slug', $slug)->with('comments')->firstOrFail();
	}

	public function savePostData(Request $request, $id)
	{
		$post = BlogPost::find($id);

        $post->title = $request->input('title');
        $post->date = $request->input('date');
        $post->body = $request->input('body');
        
        $post->save();
	}

    public function createPost(Request $request) {
        $post = new BlogPost;

        $post->title = $request->input('title');
        $post->date = $request->input('date');
        $post->body = $request->input('body');
        $post->status = $request->input('status');

        $post->save();
    }

	public function getRubrics()
	{
		include(app_path() . '/functions/datetime_formats.php');
		$rubrics = BlogRubric::orderBy('name')->get();
		return view('blog.rubrics', ['rubrics' => $rubrics]);
	}

	public function getTags()
	{
		include(app_path() . '/functions/datetime_formats.php');
		$tags = BlogTag::orderBy('name')->get();
		return view('blog.tags', ['tags' => $tags]);
	}
}

resources/views/blog/create.blade.php
@extends('layout.master')

@section('title', 'Новый пост')

@section('main_title')
	<a href="/">Бл-г</a>
@stop

@section('content')
	<div>
		{{ HTML::ul($errors->all()) }}

		{{ Form::open(array('url' => 'blog')) }}
			<div class="edit-block">
				<div>
					{{ Form::label('title', 'Заголовок') }}
					{{ Form::text('title', Input::old('title')) }}
				</div>
			</div>
			<div class="edit-block">
				{{ Form::label('slug', 'Кодовое имя') }}
				{{ Form::text('slug', Input::old('slug')) }}
			</div>
			<div class="edit-block">
				{{ Form::label('body', 'Текст') }}<br />
				{{ Form::textarea('body', Input::old('body')) }}
			</div>
			<div class="edit-block">
				{{ Form::label('status', 'Статус') }}<br />
				{{ Form::select('status', array('2' => 'Готовый пост', '1' => 'Черновик'), Input::old('status')) }}
			</div>
			<div class="edit-block double">
				<div>
					{{ Form::label('custom_date', 'Задать дату публикации вручную') }}
					{{ Form::checkbox('custom_date', null) }}
				</div>
				<div>
					{{ Form::label('date', 'Дата и время публикации') }}
					{{ Form::text('date', null) }}
				</div>
			</div>

			{{ Form::submit('Создать', array('class' => 'save')) }}
		{{ Form::close() }}
	</div>
@stop

resources/views/blog/edit.blade.php
@extends('layout.master')

@section('title')
	[Редактирование] {{ $post->title }}
@stop

@section('main_title')
	<a href="/">Бл-г</a>
@stop

@section('content')
	<div>
		{{ HTML::ul($errors->all()) }}

		{{ Form::model($post, array('route' => array('blog.update', $post->slug), 'method' => 'PUT')) }}

			<div class="edit-block">
				<div>
					{{ Form::label('title', 'Заголовок') }}
					{{ Form::text('title', null) }}
				</div>
			</div>
			<div class="edit-block">
				{{ Form::label('slug', 'Кодовое имя') }}
				{{ Form::text('slug', null) }}
			</div>
			<div class="edit-block">
				{{ Form::label('date', 'Дата публикации') }}
				{{ Form::text('date', null) }}
			</div>
			<div class="edit-block">
				{{ Form::label('status', 'Статус') }}<br />
				{{ Form::select('status', array('1' => 'Черновик', '2' => 'Готовый пост'), null) }}
			</div>
			<div class="edit-block">
				{{ Form::label('body', 'Текст') }}<br />
				{{ Form::textarea('body', null) }}
			</div>

			{{ Form::submit('Сохранить', array('class' => 'save')) }}
		{{ Form::close() }}
		
		{{ Form::open(array('url' => 'blog/' . $post->id)) }}
			{{ Form::hidden('_method', 'DELETE') }}
			{{ Form::submit('Удалить', array('class' => 'delete')) }}
		{{ Form::close() }}
	</div>
@stop

resources/views/blog/index.blade.php
@extends('layout.master')

@section('title')
	Бл-г@if ($posts->currentPage() > 1), страница {{ $posts->currentPage() }} @endif
@stop

@section('main_title')
	@if($posts->currentPage() > 1)<a href="/">@endif
	Бл-г
	@if($posts->currentPage() > 1)</a>@endif
@stop

@section('mainClass', 'blog')

@section('content')
	<style type="text/css">
		.expander {
			cursor: pointer;
		}
		h3.post-title a.edit, h1 a.create-new {
			/*display: none;*/
		}

		h3.post-title:hover a.edit, h1:hover a.create-new {
			/*display: inline !important;*/
		}
	</style>
	<h1 style="display: flex; flex-direction: column; align-items: center;">
		@if ($posts->currentPage() > 1 || $rubric || $tag || $year || $month)<a href="/">@endif
		
		Бл-г

		@if ($posts->currentPage() > 1 || $rubric || $tag || $year || $month)</a>@endif

		@if($rubric)
			<div style="font-size: 24px;">
				Посты из рубрики "@if($posts->currentPage() > 1)<a href="/rubrics/{{ $rubric->slug }}">@endif{{ $rubric->name }}@if ($posts->currentPage() > 1)</a>@endif"
			</div>
		@endif

		@if($tag)
			<div style="font-size: 24px;">
				Посты по тегу "{{ $tag->name }}"
			</div>
		@endif

		@if($month)
			<div style="font-size: 24px; font-weight: normal; display: flex; justify-content: center; align-items: center;">
				<span style="font-size: 18px">
					<a href="/{{ $year - ($month == 1) }}/{{ $month == 1 ? 12 : $month - 1 }}">{{ ru_month_nominative($month == 1 ? 12 : $month - 1) }} {{ $month == 1 ? $year - 1 : '' }}</a>
					<span style="display:inline block; margin: 0 1em;">
						&larr;
					</span>
				</span>
				
				<span>
					Посты за {{ ru_month_nominative($month) }} <a href="/{{ $year }}">{{ $year }}</a> года
				</span>

				<span style="font-size: 18px">
					<span style="display:inline block; margin: 0 1em;">
						&rarr;
					</span>
					<a href="/{{ $year + ($month == 12) }}/{{ $month == 12 ? 1 : $month + 1 }}">{{ ru_month_nominative($month == 12 ? 1 : $month + 1) }} {{ $month == 12 ? $year + 1 : '' }}</a>
				</span>
			</div>
		@elseif($year)
			<div style="font-size: 24px; font-weight: normal; display: flex; justify-content: center; align-items: center;">
				@if($year > 2006)
					<span style="font-size: 18px">
						<a href="/{{ $year - 1 }}">{{ $year - 1 }}</a>
						<span style="display:inline block; margin: 0 1em;">
							&larr;
						</span>
					</span>
				@endif
				
				<span>
					Посты за {{ $year }} год
				</span>

				@if($year < 2017)
					<span style="font-size: 18px">
						<span style="display:inline block; margin: 0 1em;">
							&rarr;
						</span>
						<a href="/{{ $year + 1 }}">{{ $year + 1 }}</a>
					</span>
				@endif
			</div>
		@endif

		@if(Auth::user() && Auth::user()->id == 1)
			<a class="create-new" href="{{ route('blog.create') }}" style="text-align: center; display: block; font-size: 16px; font-weight: normal;margin-top: .5em;"><i class="fa fa-lock"></i> Новый пост</a>
		@endif
	</h1>

	@if ($posts->currentPage() == 1 && !$rubric && !$tag && !$year && !$month)
	<div id="preface" style="margin-bottom:4em;">
		<p class="hyphenated">
			В 2006 году я завел себе нетематический ЖЖ. Наши отношения не сложились и я переехал на Блоггер (гугловский сервис). В конце концов природная склонность сделать так, как мне нравится, породила мой собственный блог на моем собственном сайте.
		</p>
		<p class="hyphenated">
			Некоторые посты старого блога, объединенные одной темой, составили целые разделы на сайте (<a href="/outdoors">Поездки</a>, <a href="/rest">Рестораны</a>, <a href="/hrenotive">Хренотив</a>, <a href="/notebook">Записная книжка</a> и <a href="/zhitie">Житие Шухера</a>).
		<p>
		<p>
			Сегодня я все меньше пишу в блог и все больше пишу в <a href="https://www.facebook.com/birenbergg">фейсбук</a>. Во-первых, там удобнее; во-вторых, там во много раз больший фидбек; в-третьих, там можно мусорить как угодно (а избранные посты из фейсбука и так публикуются здесь).
		</p>
		<p>* * *</p>
		<p>NB Мнение автора в {{ date('Y') }}-м году может не совпадать со мнением автора в {{ rand(2006, (date('Y') - 1)) }}-м.</p>
	</div>
	@endif
	
	<div style="display: flex;">
		<div style="width: 73%; width: auto;">
			@if(count($posts))
				@foreach($posts as $post)
					<div class="post{{ $post->status == 1 ? ' hidden-post' : '' }}">
						<div style="display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 2em;">
							<a href="/{{ $post->slug }}" style="color: #999;">
								<h3 class="post-title" style="font-weight: normal">
									{!! $post->title !!}

									@if($post->rubric && false)
										<div style="text-align:center;color: #ccc;font-weight: normal;font-size: 18px;margin-top: .5em;">Из рубрики "<a style="color:#63aac7" href="/rubrics/{{ $post->rubric->slug }}">{{ $post->rubric->name }}</a>" {{ Auth::check() ? 'rubric id: ' . $post->rubric->id : '' }}</div>
									@endif
								</h3>
							</a>
							<span>
								<date class="post-date" style="margin-bottom: 0">{{ full_ru_datetime($post->date) }}</date>
							</span>
						</div>
						<div class="post-body">{!! $post->body !!}</div>
						@if(count($post->tags) > 0)
							@include('includes.tags')
						@endif

						@if(Auth::user() && Auth::user()->id == 1)
							<a class="edit" href="/blog/{{ $post->slug }}/edit" title="Редактировать"><i class="fa fa-lock"></i> Редактировать</a>
						@endif

						@if(Auth::user() && Auth::user()->id == 1 && count($post->comments) > 0)
						|
						@endif

						<a href="/{{ $post->slug }}#comments">
							@if(count($post->comments) > 0)
								Читать @php echo pluralization(count($post->comments), 'камент камента каментов', true) @endphp или написать свой
							@else
								<!-- <i class="fa fa-comment"></i>
								Написать камент -->
							@endif
						</a>
					</div>
				@endforeach
			@else
				Ничего не найдено.
			@endif
		</div>
		<div style="width: 23%; margin-left: 4em; display: none;">
			<div style="border-top: 1px dotted #999; margin-bottom:2em;">
				<h4>Машина времени</h4>
				<div>
					<ul style="list-style: none; padding: 0;">
					@for ($i = 2017; $i >= 2006; $i--)
						<li>
							<span style="width: 1em; display: inline-block;" id="y{{$i}}-expander" class="expander {{ $i == $year ? 'open' : 'closed' }}" data-list="y{{$i}}-month-list">
								@if($i == $year)
									<i class="fa fa-caret-down"></i>
								@else
									<i class="fa fa-caret-right"></i>
								@endif
							</span>

							@if((!$month && !$year) || $month || $year && !($i == $year))
								<a href="/{{ $i }}">
							@endif

								{{ $i }}

							@if((!$month && !$year) || $month || $year && !($i == $year))
								</a>
							@endif
							<ul style="display: {{ $i == $year ? 'block' : 'none' }}; list-style: none;" id="y{{$i}}-month-list">
								@for ($j = 12; $j >= 1; $j--)
									<li>
										@if((!$month && !$year) || ($year || $month) && !($i == $year && $j == $month))
											<a href="/{{ $i }}/{{ $j }}">
										@endif

											{{ ru_month_nominative($j) }}

										@if((!$month && !$year) || ($year || $month) && !($i == $year && $j == $month))
											</a>
										@endif
									</li>
								@endfor
							</ul>
						</li>
					@endfor
					</ul>
				</div>
			</div>
			<div style="border-top: 1px dotted #999; margin-bottom:2em;">
				<h4><a href="/rubrics">Рубрики</a></h4>
				<ul style="list-style: none; padding: 0;">
					@foreach($rubrics as $rubric)
						<li><a href="/rubrics/{{ $rubric->slug }}">{{ $rubric->name }}</a> ({{ $rubric->posts_count }})</li>
					@endforeach
				</ul>
			</div>
			<div style="border-top: 1px dotted #999; margin-bottom:2em;">
				<h4><a href="/tags">Теги</a></h4>
				<div>
					@foreach($tags as $tag)
						<a style="font-size: {{ $tag->posts_count + 14 }}px" href="/tags/{{ $tag->slug }}">{{ $tag->name }}</a>
					@endforeach
				</div>
			</div>
		</div>
	</div>
	@if ($posts->lastPage() > 1)
	<div style="text-align: center; font-size: 18px; color: #ccc; margin-top:1em;">
		<div>страница:</div>
		<div style="text-align:center;">
			{!! $posts->render() !!}
		</div>
	</div>
	@endif

	<script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
	<script type="text/javascript">
		$('.expander').click(function() {
			if ($(this).hasClass('closed')) {
				$('#' + $(this).data('list')).css('display', 'block');
				$(this).removeClass('closed');
				$(this).addClass('open');
				$(this).html('<i class="fa fa-caret-down"></i>');
			} else if($(this).hasClass('open')) {
				$('#' + $(this).data('list')).css('display', 'none');
				$(this).removeClass('open');
				$(this).addClass('closed');
				$(this).html('<i class="fa fa-caret-right"></i>');
			}
		});
	</script>
@stop

resources/views/blog/rubrics.blade.php
@extends('layout.master')
@section('title', 'Рубрики Бл-га')
@section('mainClass', 'blog')

@section('main_title')
	Рубрики <a href="/">Бл-га</a>
@stop

@section('content')
	<h1>
		Рубрики <a href="/">Бл-га</a>
	</h1>
	<ul>
		@foreach($rubrics as $rubric)
			@if(count($rubric->posts) > 0)<li><a href="/rubrics/{{ $rubric->slug }}">{{ $rubric->name }}</a> {{ count($rubric->posts) }}</li>@endif
		@endforeach
	</ul>
@stop

resources/views/blog/show.blade.php
@extends('layout.master')

@section('title')
	{{ $post->title }}
@stop

@section('main_title')
	<a href="/">Бл-г</a>
@stop

@section('content')
	<style type="text/css">
		h2.post-title a {
			display: none;
		}

		h2.post-title:hover a {
			display: inline !important;
		}

		#comments h3 {
			text-align: left;
			margin-bottom: 0.5em;
			margin-top: 2em;
		}

		#comments h4 {
			background: #abc;
			margin: 0;
			display: inline;
			border: 0;
			padding: .25em .75em;
			border-radius: 8px 8px 0 0;
		}
		#comments blockquote {
			border: 0;
			background: #abc;
			border-radius: 0 8px 8px 8px;
		}

		#comments .commentus {
			margin-bottom: 2em;
		}
	</style>
	<div>
		<h2 class="post-title">
			{{ $post->title }}
			@if(Auth::user() && Auth::user()->id == 1)
				<a href="/blog/{{ $post->slug }}/edit" title="Редактировать"><i class="fa fa-pencil"></i></a>
			@endif				
		</h2>
		<date class="post-date">{{ full_ru_datetime($post->date) }}</date>

		@if($post->rubric)
		<div style="text-align:center;color: #ccc;font-weight: normal;font-size: 18px;margin-top: .5em;">Из рубрики "<a style="color:#63aac7" href="/rubrics/{{ $post->rubric->slug }}">{{ $post->rubric->name }}</a>" rubric id: {{ Auth::check() ? $post->rubric->id : '' }}</div>
		@endif
		<div class="post-body">{!! $post->body !!}</div>
		@if(count($post->tags) > 0)
			@include('includes.tags')
		@endif

		@if(count($post->comments) > 0)
			<div id="comments">
				<h3>@php echo pluralization(count($post->comments), 'камент камента каментов', true) @endphp</h3>
				@foreach ($post->comments as $comment)
					<div class="commentus">
						<h4>
							{{ $comment->poster_name }}
							<date>{{ full_ru_datetime($comment->date) }}</date>
						</h4>
						<blockquote>
							{!! $comment->body !!}
						</blockquote>
					</div>
				@endforeach
			</div>
		@endif
	</div>
@stop

resources/views/blog/tags.blade.php
@extends('layout.master')
@section('title', 'Теги Бл-га')
@section('mainClass', 'blog')

@section('main_title')
	Теги <a href="/">Бл-га</a>
@stop

@section('content')
	<h1>
		Теги <a href="/">Бл-га</a>
	</h1>
	<ul>
		@foreach($tags as $tag)
			@if(count($tag->posts) > 0)
				<li><a href="/tags/{{ $tag->slug }}">{{ $tag->name }}</a> {{ count($tag->posts) }}</li>
			@endif
		@endforeach
	</ul>
@stop